"use client";

import { useResumes, type UserResume } from "@/lib/hooks/use-resumes";
import { Button, Spinner } from "@heroui/react";
import {
    IconArrowRight,
    IconCheck,
    IconFile,
    IconSparkles,
} from "@tabler/icons-react";
import clsx from "clsx";
import Image from "next/image";
import NextLink from "next/link";
import { useState } from "react";

interface PortfolioWizardProps {
    onGenerate: (html: string) => void;
    isGenerating: boolean;
    setIsGenerating: (generating: boolean) => void;
}

const TEMPLATES = [
    { id: "minimal", name: "Minimalist", image: "/templates/image-1.png" },
    { id: "creative", name: "Creative", image: "/templates/image-2.png" },
    { id: "professional", name: "Professional", image: "/templates/image-3.png" },
    { id: "modern", name: "Modern", image: "/templates/image-4.png" },
];

export function PortfolioWizard({
    onGenerate,
    isGenerating,
    setIsGenerating,
}: PortfolioWizardProps) {
    const [step, setStep] = useState<"template" | "resume">("template");
    const [selectedTemplate, setSelectedTemplate] = useState<string | null>(
        null,
    );
    const [selectedResume, setSelectedResume] = useState<UserResume | null>(
        null,
    );

    const { resumes, isLoading: isResumesLoading } = useResumes();

    const handleGenerate = async () => {
        if (!selectedTemplate || !selectedResume) return;

        setIsGenerating(true);
        // Simulate LLM call
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            onGenerate(`
                <div style="width: 100vw; height: 100vh; display: flex; align-items: center; justify-content: center; background: #f0f0f0; color: black; font-family: sans-serif;">
                    <div style="text-align: center;">
                        <h1 style="font-size: 4rem; margin-bottom: 1rem;">${selectedResume.name}</h1>
                        <p style="font-size: 1.5rem;">${selectedTemplate} Portfolio</p>
                        <p>Generated by Feno AI</p>
                    </div>
                </div>
            `);
        } finally {
            setIsGenerating(false);
        }
    };

    if (isGenerating) {
        return (
            <div className="flex-1 flex flex-col items-center justify-center p-8 text-center h-full">
                <Spinner
                    size="lg"
                    color="current"
                    className="mb-4 text-black"
                />
                <h3 className="text-xl font-medium mb-2">
                    Generating your portfolio...
                </h3>
                <p className="text-black/60 max-w-md">
                    We are crafting a beautiful website based on your resume and
                    chosen style. This usually takes about 30 seconds.
                </p>
            </div>
        );
    }

    return (
        <div className="flex-1 flex flex-col h-full">
            <div className="border-b border-black/5 px-6 py-4 flex items-center justify-between shrink-0">
                <h2 className="text-lg font-semibold">
                    {step === "template"
                        ? "Choose a Style"
                        : "Select Content Source"}
                </h2>
                <div className="flex gap-2 text-sm text-black/40">
                    <span
                        className={clsx(
                            step === "template" && "text-black font-medium",
                        )}
                    >
                        1. Style
                    </span>
                    <span>/</span>
                    <span
                        className={clsx(
                            step === "resume" && "text-black font-medium",
                        )}
                    >
                        2. Content
                    </span>
                </div>
            </div>

            <div className="flex-1 overflow-y-auto p-6 min-h-0">
                {step === "template" ? (
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                        {TEMPLATES.map((template) => (
                            <button
                                type="button"
                                key={template.id}
                                onClick={() => setSelectedTemplate(template.id)}
                                className={clsx(
                                    "group relative rounded-xl border-2 overflow-hidden transition-all text-left",
                                    selectedTemplate === template.id
                                        ? "border-black ring-2 ring-black/5 ring-offset-2"
                                        : "border-transparent hover:border-black/10 bg-black/5",
                                )}
                            >
                                <div className="aspect-[16/10] relative bg-white">
                                    <Image
                                        src={template.image}
                                        alt={template.name}
                                        fill
                                        className="object-cover"
                                    />
                                    <div className="absolute inset-0 bg-black/0 group-hover:bg-black/5 transition-colors" />
                                </div>
                                <div className="p-3 bg-white border-t border-black/5">
                                    <span className="font-medium text-sm">
                                        {template.name}
                                    </span>
                                </div>
                                {selectedTemplate === template.id && (
                                    <div className="absolute top-2 right-2 bg-black text-white rounded-full p-1 shadow-lg z-10">
                                        <IconCheck size={14} />
                                    </div>
                                )}
                            </button>
                        ))}
                    </div>
                ) : (
                    <div className="max-w-2xl mx-auto space-y-4 w-full">
                        {isResumesLoading ? (
                            <div className="text-center py-12">
                                <Spinner size="lg" />
                            </div>
                        ) : resumes.length === 0 ? (
                            <div className="text-center py-12 border-2 border-dashed border-black/10 rounded-xl">
                                <p className="mb-4 text-black/60">
                                    No resumes found.
                                </p>
                                <NextLink href="/resume">
                                    <Button variant="ghost">
                                        Create Resume
                                    </Button>
                                </NextLink>
                            </div>
                        ) : (
                            <div className="grid gap-3">
                                {resumes.map((resume) => (
                                    <button
                                        type="button"
                                        key={resume.id}
                                        onClick={() => setSelectedResume(resume)}
                                        className={clsx(
                                            "flex items-center gap-4 p-4 rounded-xl border transition-all text-left w-full",
                                            selectedResume?.id === resume.id
                                                ? "border-black bg-black/5"
                                                : "border-black/10 hover:border-black/30 bg-white",
                                        )}
                                    >
                                        <div className="p-3 bg-white rounded-lg border border-black/5 text-black/60 shrink-0">
                                            <IconFile size={24} />
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <h3 className="font-medium truncate">
                                                {resume.name}
                                            </h3>
                                            <p className="text-sm text-black/50">
                                                Last updated:{" "}
                                                {new Date(
                                                    resume.updated_at,
                                                ).toLocaleDateString()}
                                            </p>
                                        </div>
                                        {selectedResume?.id === resume.id && (
                                            <div className="text-black shrink-0">
                                                <IconCheck size={20} />
                                            </div>
                                        )}
                                    </button>
                                ))}
                            </div>
                        )}
                    </div>
                )}
            </div>

            <div className="border-t border-black/5 p-4 flex justify-between items-center bg-white shrink-0">
                {step === "resume" ? (
                    <Button variant="ghost" onPress={() => setStep("template")}>
                        Back
                    </Button>
                ) : (
                    <div />
                )}

                {step === "template" ? (
                    <Button
                        className="bg-black text-white"
                        isDisabled={!selectedTemplate}
                        onPress={() => setStep("resume")}
                    >
                        Next: Select Content <IconArrowRight size={16} />
                    </Button>
                ) : (
                    <Button
                        className="bg-black text-white"
                        isDisabled={!selectedResume}
                        onPress={handleGenerate}
                    >
                        Generate Portfolio <IconSparkles size={16} />
                    </Button>
                )}
            </div>
        </div>
    );
}
